/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ../public/temple21.glb 
*/

import React from "react";
import { useGraph, useLoader } from "@react-three/fiber";
import { useGLTF, useTexture, PerspectiveCamera } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import * as THREE from "three";

export function TempModel(props) {
  const { scene } = useGLTF("https://3dmodelpriya.s3.ap-south-1.amazonaws.com/temple21.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  //initializing the loader
  const textureLoader = new THREE.TextureLoader();

  //initializing the texture
  const marbleTexture = textureLoader.load("/textures/white_marble.jpeg");

  //initialize material
  const marbleMaterial = new THREE.MeshBasicMaterial({ map: marbleTexture });

  // Loding textures
  // const marbleTexture = useTexture("/textures/white_marble.jpeg");

  // applying Loaded texture
  // if (materials["white_Marble"]) {
  //   materials["white_Marble"].map = marbleTexture;
  //   materials["white_Marble"].map.needsUpdate = true;
  // }

  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[69.531, 5.486, -2.705]}
        rotation={[2.025, 1.408, -2.032]}
        scale={[2.449, 4.77, 2.503]}
      />
      <pointLight intensity={8} decay={2} position={[3.514, 26.466, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1.633} />
      <directionalLight
        intensity={7}
        decay={2}
        position={[0, 65.944, -32.715]}
        rotation={[-2.113, 0.007, 0]}
        scale={3.74}
        target={nodes.Sun.target}
      >
        <primitive object={nodes.Sun.target} position={[0, 0, -1]} />
      </directionalLight>
      <group position={[2.986, 56.505, -0.881]} scale={[0.069, 7.234, 0.157]}>
        // large gallery floor
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Wood} />
        // flag cloth
        <mesh geometry={nodes.Cube001_2.geometry} material={materials["Red Marble"]} />
        //the roof whole outside wall, large gallery roof
        {/* <mesh geometry={nodes.Cube001_3.geometry} material={materials["Black and gold marble.011"]} /> */}
        {/* <mesh geometry={nodes.Cube001_3.geometry} material={materials["Marble.035"]} /> */}
        <mesh geometry={nodes.Cube001_3.geometry} material={materials["Red Marble"]} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials["Golden brushed metal.008"]} />
        <mesh geometry={nodes.Cube001_5.geometry} material={materials["Golden Honeycomb.008"]} />
        <mesh geometry={nodes.Cube001_6.geometry} material={materials["Ceramic Tile Golden.008"]} />
        <mesh geometry={nodes.Cube001_7.geometry} material={materials["Black and gold marble.008"]} />
        <mesh geometry={nodes.Cube001_8.geometry} material={materials["Marble.011"]} />
        <mesh geometry={nodes.Cube001_9.geometry} material={materials["Golden brushed metal.009"]} />
        <mesh geometry={nodes.Cube001_10.geometry} material={materials["Golden Honeycomb.009"]} />
        <mesh geometry={nodes.Cube001_11.geometry} material={materials["Ceramic Tile Golden.009"]} />
        <mesh geometry={nodes.Cube001_12.geometry} material={materials["Black and gold marble.009"]} />
        <mesh geometry={nodes.Cube001_13.geometry} material={materials["Marble.012"]} />
        <mesh geometry={nodes.Cube001_14.geometry} material={materials["Golden brushed metal.010"]} />
        <mesh geometry={nodes.Cube001_15.geometry} material={materials["Golden Honeycomb.010"]} />
        <mesh geometry={nodes.Cube001_16.geometry} material={materials["Ceramic Tile Golden.010"]} />
        <mesh geometry={nodes.Cube001_17.geometry} material={materials["Black and gold marble.010"]} />
        <mesh geometry={nodes.Cube001_18.geometry} material={materials["Marble.013"]} />
        <mesh geometry={nodes.Cube001_19.geometry} material={materials["Golden brushed metal.011"]} />
        <mesh geometry={nodes.Cube001_20.geometry} material={materials["Golden Honeycomb.011"]} />
        <mesh geometry={nodes.Cube001_21.geometry} material={materials["Ceramic Tile Golden.011"]} />
        <mesh geometry={nodes.Cube001_22.geometry} material={materials["Black and gold marble.011"]} />
      </group>
      //sheet under shiv ji
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Red Marble"]}
        position={[3.461, 6.505, 0.0003]}
        scale={[2.166, 1.895, 2.95]}
      />
      //shiv ji, lower stones
      <group position={[3.555, 8.758, 0.114]} rotation={[-Math.PI, 1.209, -Math.PI]} scale={[1.967, 0.431, 2.339]}>
        <mesh geometry={nodes.Sphere_1.geometry} material={materials["Brown marble"]} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials.Marble} />
        {/* <mesh geometry={nodes.Sphere_3.geometry} material={materials["Black veined marble"]} /> */}
        // shiv ji
        <mesh
          geometry={nodes.Sphere_3.geometry}
          material={materials["Cast Iron Wrought Pattern Diamond.005"]}
          position={[0.002, -4.758, 0.0114]}
          scale={[1.0037, 3.0431, 1.059]}
        />
      </group>
      <group position={[-9.529, 16.308, 10.87]} scale={[1.067, 0.048, 0.913]}>
        <mesh geometry={nodes.Cube005_1.geometry} material={materials["White Bronze Marble"]} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials["Black Marble Procedural"]} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials["Dark Brown Marble"]} />
      </group>
      <group position={[-10.868, 17.856, 11.96]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus_1.geometry} material={materials["Marble.002"]} />
        <mesh geometry={nodes.Torus_2.geometry} material={materials["Golden brushed metal"]} />
        <mesh geometry={nodes.Torus_3.geometry} material={materials["Golden Honeycomb"]} />
        <mesh geometry={nodes.Torus_4.geometry} material={materials["Ceramic Tile Golden"]} />
        <mesh geometry={nodes.Torus_5.geometry} material={materials["Black and gold marble"]} />
      </group>
      <group position={[-10.882, 17.829, 9.764]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus003_1.geometry} material={materials["Marble.003"]} />
        <mesh geometry={nodes.Torus003_2.geometry} material={materials["Golden brushed metal.001"]} />
        <mesh geometry={nodes.Torus003_3.geometry} material={materials["Golden Honeycomb.001"]} />
        <mesh geometry={nodes.Torus003_4.geometry} material={materials["Ceramic Tile Golden.001"]} />
        <mesh geometry={nodes.Torus003_5.geometry} material={materials["Black and gold marble.001"]} />
      </group>
      <group position={[-8.208, 17.863, 9.74]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus004.geometry} material={materials["Marble.004"]} />
        <mesh geometry={nodes.Torus004_1.geometry} material={materials["Golden brushed metal.002"]} />
        <mesh geometry={nodes.Torus004_2.geometry} material={materials["Golden Honeycomb.002"]} />
        <mesh geometry={nodes.Torus004_3.geometry} material={materials["Ceramic Tile Golden.002"]} />
        <mesh geometry={nodes.Torus004_4.geometry} material={materials["Black and gold marble.002"]} />
      </group>
      <group position={[-8.198, 17.843, 11.952]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus005.geometry} material={materials["Marble.005"]} />
        <mesh geometry={nodes.Torus005_1.geometry} material={materials["Golden brushed metal.003"]} />
        <mesh geometry={nodes.Torus005_2.geometry} material={materials["Golden Honeycomb.003"]} />
        <mesh geometry={nodes.Torus005_3.geometry} material={materials["Ceramic Tile Golden.003"]} />
        <mesh geometry={nodes.Torus005_4.geometry} material={materials["Black and gold marble.003"]} />
      </group>
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[-9.544, 19.307, 10.881]}
        scale={[0.759, 0.028, 0.689]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials["Black marble tiles with golden ornaments"]}
        position={[-9.544, 19.307, 10.881]}
        scale={[0.759, 0.028, 0.689]}
      />
      <group position={[-7.828, 21.25, 12.324]} rotation={[0, 1.566, 0]} scale={[0.018, 0.041, 0.017]}>
        <mesh geometry={nodes.Torus009.geometry} material={materials["Marble.009"]} />
        <mesh geometry={nodes.Torus009_1.geometry} material={materials["Golden brushed metal.007"]} />
        <mesh geometry={nodes.Torus009_2.geometry} material={materials["Golden Honeycomb.007"]} />
        <mesh geometry={nodes.Torus009_3.geometry} material={materials["Ceramic Tile Golden.007"]} />
        <mesh geometry={nodes.Torus009_4.geometry} material={materials["Black and gold marble.007"]} />
        <mesh geometry={nodes.Torus009_5.geometry} material={materials["Marble.006"]} />
        <mesh geometry={nodes.Torus009_6.geometry} material={materials["Golden brushed metal.004"]} />
        <mesh geometry={nodes.Torus009_7.geometry} material={materials["Golden Honeycomb.004"]} />
        <mesh geometry={nodes.Torus009_8.geometry} material={materials["Ceramic Tile Golden.004"]} />
        <mesh geometry={nodes.Torus009_9.geometry} material={materials["Black and gold marble.004"]} />
        <mesh geometry={nodes.Torus009_10.geometry} material={materials["Marble.007"]} />
        <mesh geometry={nodes.Torus009_11.geometry} material={materials["Golden brushed metal.005"]} />
        <mesh geometry={nodes.Torus009_12.geometry} material={materials["Golden Honeycomb.005"]} />
        <mesh geometry={nodes.Torus009_13.geometry} material={materials["Ceramic Tile Golden.005"]} />
        <mesh geometry={nodes.Torus009_14.geometry} material={materials["Black and gold marble.005"]} />
        <mesh geometry={nodes.Torus009_15.geometry} material={materials["Marble.008"]} />
        <mesh geometry={nodes.Torus009_16.geometry} material={materials["Golden brushed metal.006"]} />
        <mesh geometry={nodes.Torus009_17.geometry} material={materials["Golden Honeycomb.006"]} />
        <mesh geometry={nodes.Torus009_18.geometry} material={materials["Ceramic Tile Golden.006"]} />
        <mesh geometry={nodes.Torus009_19.geometry} material={materials["Black and gold marble.006"]} />
      </group>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Black Marble"]}
        position={[-9.529, 16.308, 10.87]}
        scale={[0.868, 0.039, 0.742]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Misty Veil Marble"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Pink Marble"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Marble tiles 9"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Marble.037"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Blue marble"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials["Marble Tile 2"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials["Marble Tile"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials["Luxury marble"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials["Procedural Marble Tiles"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials["White marble"]}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.white_marble}
        position={[-9.529, 21.667, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      //pillar flower
      <mesh
        geometry={nodes.Cylinder013.geometry}
        // material={materials["Marble.014"]}
        material={materials["White Bronze Marble.003"]}
        position={[-9.529, 0.998, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[-9.529, 8.959, 10.87]}
        rotation={[0, 0, 0.012]}
        scale={[1.013, 1.348, 1.071]}
      />
      {/* ground floor */}
      <group position={[3.318, 6.312, -0.3991]} scale={[4.329, 0.099, 3.502]}>
        {/* <mesh geometry={nodes.Cube012_1.geometry} material={materials["White Bronze Marble.001"]} /> */}
        {/* <mesh geometry={nodes.Cube012_1.geometry} material={materials["Black and gold marble.011"]} /> */}
        <mesh geometry={nodes.Cube012_1.geometry} material={materials["Misty Veil Marble.002"]} />

        {/* <mesh geometry={nodes.Cube012_2.geometry} material={materials["Black Marble Procedural.001"]} />
        <mesh geometry={nodes.Cube012_3.geometry} material={materials["Dark Brown Marble.001"]} /> */}
      </group>
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[-9.529, 21.408, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={nodes.Cylinder016.material}
        position={[-9.529, -3.255, 10.87]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Black murble"]}
        position={[-9.529, 16.308, 10.87]}
        scale={[1.067, 0.048, 0.913]}
      />
      <group position={[-11.79, 21.177, -9.037]} scale={[0.017, 0.041, 0.018]}>
        <mesh geometry={nodes.Torus002_1.geometry} material={materials["Marble.016"]} />
        <mesh geometry={nodes.Torus002_2.geometry} material={materials["Golden brushed metal.013"]} />
        <mesh geometry={nodes.Torus002_3.geometry} material={materials["Golden Honeycomb.013"]} />
        <mesh geometry={nodes.Torus002_4.geometry} material={materials["Ceramic Tile Golden.013"]} />
        <mesh geometry={nodes.Torus002_5.geometry} material={materials["Black and gold marble.013"]} />
        <mesh geometry={nodes.Torus002_6.geometry} material={materials["Marble.015"]} />
        <mesh geometry={nodes.Torus002_7.geometry} material={materials["Golden brushed metal.012"]} />
        <mesh geometry={nodes.Torus002_8.geometry} material={materials["Golden Honeycomb.012"]} />
        <mesh geometry={nodes.Torus002_9.geometry} material={materials["Ceramic Tile Golden.012"]} />
        <mesh geometry={nodes.Torus002_10.geometry} material={materials["Black and gold marble.012"]} />
        <mesh geometry={nodes.Torus002_11.geometry} material={materials["Marble.018"]} />
        <mesh geometry={nodes.Torus002_12.geometry} material={materials["Golden brushed metal.014"]} />
        <mesh geometry={nodes.Torus002_13.geometry} material={materials["Golden Honeycomb.014"]} />
        <mesh geometry={nodes.Torus002_14.geometry} material={materials["Ceramic Tile Golden.014"]} />
        <mesh geometry={nodes.Torus002_15.geometry} material={materials["Black and gold marble.014"]} />
        <mesh geometry={nodes.Torus002_16.geometry} material={materials["Marble.019"]} />
        <mesh geometry={nodes.Torus002_17.geometry} material={materials["Golden brushed metal.015"]} />
        <mesh geometry={nodes.Torus002_18.geometry} material={materials["Golden Honeycomb.015"]} />
        <mesh geometry={nodes.Torus002_19.geometry} material={materials["Ceramic Tile Golden.015"]} />
        <mesh geometry={nodes.Torus002_20.geometry} material={materials["Black and gold marble.015"]} />
      </group>
      <group position={[-8.826, 17.769, -9.534]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus016_1.geometry} material={materials["Marble.020"]} />
        <mesh geometry={nodes.Torus016_2.geometry} material={materials["Golden brushed metal.016"]} />
        <mesh geometry={nodes.Torus016_3.geometry} material={materials["Golden Honeycomb.016"]} />
        <mesh geometry={nodes.Torus016_4.geometry} material={materials["Ceramic Tile Golden.016"]} />
        <mesh geometry={nodes.Torus016_5.geometry} material={materials["Black and gold marble.016"]} />
      </group>
      <group position={[-8.835, 17.789, -11.745]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus017_1.geometry} material={materials["Marble.021"]} />
        <mesh geometry={nodes.Torus017_2.geometry} material={materials["Golden brushed metal.017"]} />
        <mesh geometry={nodes.Torus017_3.geometry} material={materials["Golden Honeycomb.017"]} />
        <mesh geometry={nodes.Torus017_4.geometry} material={materials["Ceramic Tile Golden.017"]} />
        <mesh geometry={nodes.Torus017_5.geometry} material={materials["Black and gold marble.017"]} />
      </group>
      <group position={[-11.51, 17.755, -11.721]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus018_1.geometry} material={materials["Marble.022"]} />
        <mesh geometry={nodes.Torus018_2.geometry} material={materials["Golden brushed metal.018"]} />
        <mesh geometry={nodes.Torus018_3.geometry} material={materials["Golden Honeycomb.018"]} />
        <mesh geometry={nodes.Torus018_4.geometry} material={materials["Ceramic Tile Golden.018"]} />
        <mesh geometry={nodes.Torus018_5.geometry} material={materials["Black and gold marble.018"]} />
      </group>
      <group position={[-11.496, 17.782, -9.526]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus019_1.geometry} material={materials["Marble.023"]} />
        <mesh geometry={nodes.Torus019_2.geometry} material={materials["Golden brushed metal.019"]} />
        <mesh geometry={nodes.Torus019_3.geometry} material={materials["Golden Honeycomb.019"]} />
        <mesh geometry={nodes.Torus019_4.geometry} material={materials["Ceramic Tile Golden.019"]} />
        <mesh geometry={nodes.Torus019_5.geometry} material={materials["Black and gold marble.019"]} />
      </group>
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[-10.156, -3.329, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
        position={[-10.156, 21.334, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[-10.156, 8.885, -10.615]}
        rotation={[0, 0, 0.012]}
        scale={[1.013, 1.348, 1.071]}
      />
      // pillar flower
      <mesh
        geometry={nodes.Cylinder019.geometry}
        // material={materials["Marble.024"]}
        material={materials["White Bronze Marble.003"]}
        position={[-10.156, 0.924, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials["white_marble.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials["White marble.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials["Procedural Marble Tiles.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials["Luxury marble.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials["Marble Tile.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials["Marble Tile 2.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials["Blue marble.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={materials["Marble.025"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={materials["Marble tiles 9.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder029.geometry}
        material={materials["Pink Marble.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={materials["Misty Veil Marble.001"]}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[-10.156, 21.593, -10.615]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Black murble.001"]}
        position={[-10.156, 16.234, -10.615]}
        scale={[1.067, 0.048, 0.913]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[-10.171, 19.234, -10.605]}
        scale={[0.759, 0.028, 0.689]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Black Marble.001"]}
        position={[-10.156, 16.234, -10.615]}
        scale={[0.868, 0.039, 0.742]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Black marble tiles with golden ornaments.001"]}
        position={[-10.171, 19.234, -10.605]}
        scale={[0.759, 0.028, 0.689]}
      />
      <group position={[-10.156, 16.234, -10.615]} scale={[1.067, 0.048, 0.913]}>
        <mesh geometry={nodes.Cube008_1.geometry} material={materials["White Bronze Marble.002"]} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials["Black Marble Procedural.002"]} />
        <mesh geometry={nodes.Cube008_3.geometry} material={materials["Dark Brown Marble.002"]} />
      </group>
      //trishul small
      <group position={[19.053, 2.67, -16.395]} rotation={[0, 0.027, 0]} scale={[3.59, 5.589, 3.962]}>
        <mesh geometry={nodes.Circle001_1.geometry} material={materials["Cast Iron Wrought Pattern Diamond.001"]} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials["Cast Iron Wrought Pattern Diamond.001"]} />
        <mesh geometry={nodes.Circle001_3.geometry} material={materials["White Bronze Marble.003"]} />
      </group>
      <group position={[15.458, 18.135, -10.179]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus020_1.geometry} material={materials["Marble.026"]} />
        <mesh geometry={nodes.Torus020_2.geometry} material={materials["Golden brushed metal.020"]} />
        <mesh geometry={nodes.Torus020_3.geometry} material={materials["Golden Honeycomb.020"]} />
        <mesh geometry={nodes.Torus020_4.geometry} material={materials["Ceramic Tile Golden.020"]} />
        <mesh geometry={nodes.Torus020_5.geometry} material={materials["Black and gold marble.020"]} />
      </group>
      <group position={[15.444, 18.108, -12.374]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus021_1.geometry} material={materials["Marble.027"]} />
        <mesh geometry={nodes.Torus021_2.geometry} material={materials["Golden brushed metal.021"]} />
        <mesh geometry={nodes.Torus021_3.geometry} material={materials["Golden Honeycomb.021"]} />
        <mesh geometry={nodes.Torus021_4.geometry} material={materials["Ceramic Tile Golden.021"]} />
        <mesh geometry={nodes.Torus021_5.geometry} material={materials["Black and gold marble.021"]} />
      </group>
      <group position={[18.119, 18.142, -12.398]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus022_1.geometry} material={materials["Marble.028"]} />
        <mesh geometry={nodes.Torus022_2.geometry} material={materials["Golden brushed metal.022"]} />
        <mesh geometry={nodes.Torus022_3.geometry} material={materials["Golden Honeycomb.022"]} />
        <mesh geometry={nodes.Torus022_4.geometry} material={materials["Ceramic Tile Golden.022"]} />
        <mesh geometry={nodes.Torus022_5.geometry} material={materials["Black and gold marble.022"]} />
      </group>
      <group position={[18.231, 18.124, -10.061]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus023_1.geometry} material={materials["Marble.029"]} />
        <mesh geometry={nodes.Torus023_2.geometry} material={materials["Golden brushed metal.023"]} />
        <mesh geometry={nodes.Torus023_3.geometry} material={materials["Golden Honeycomb.023"]} />
        <mesh geometry={nodes.Torus023_4.geometry} material={materials["Ceramic Tile Golden.023"]} />
        <mesh geometry={nodes.Torus023_5.geometry} material={materials["Black and gold marble.023"]} />
      </group>
      <group position={[15.061, 21.53, -9.715]} rotation={[0, 1.566, 0]} scale={[0.018, 0.041, 0.017]}>
        <mesh geometry={nodes.Torus025_1.geometry} material={materials["Marble.031"]} />
        <mesh geometry={nodes.Torus025_2.geometry} material={materials["Golden brushed metal.025"]} />
        <mesh geometry={nodes.Torus025_3.geometry} material={materials["Golden Honeycomb.025"]} />
        <mesh geometry={nodes.Torus025_4.geometry} material={materials["Ceramic Tile Golden.025"]} />
        <mesh geometry={nodes.Torus025_5.geometry} material={materials["Black and gold marble.025"]} />
        <mesh geometry={nodes.Torus025_6.geometry} material={materials["Marble.030"]} />
        <mesh geometry={nodes.Torus025_7.geometry} material={materials["Golden brushed metal.024"]} />
        <mesh geometry={nodes.Torus025_8.geometry} material={materials["Golden Honeycomb.024"]} />
        <mesh geometry={nodes.Torus025_9.geometry} material={materials["Ceramic Tile Golden.024"]} />
        <mesh geometry={nodes.Torus025_10.geometry} material={materials["Black and gold marble.024"]} />
        <mesh geometry={nodes.Torus025_11.geometry} material={materials["Marble.032"]} />
        <mesh geometry={nodes.Torus025_12.geometry} material={materials["Golden brushed metal.026"]} />
        <mesh geometry={nodes.Torus025_13.geometry} material={materials["Golden Honeycomb.026"]} />
        <mesh geometry={nodes.Torus025_14.geometry} material={materials["Ceramic Tile Golden.026"]} />
        <mesh geometry={nodes.Torus025_15.geometry} material={materials["Black and gold marble.026"]} />
        <mesh geometry={nodes.Torus025_16.geometry} material={materials["Marble.033"]} />
        <mesh geometry={nodes.Torus025_17.geometry} material={materials["Golden brushed metal.027"]} />
        <mesh geometry={nodes.Torus025_18.geometry} material={materials["Golden Honeycomb.027"]} />
        <mesh geometry={nodes.Torus025_19.geometry} material={materials["Ceramic Tile Golden.027"]} />
        <mesh geometry={nodes.Torus025_20.geometry} material={materials["Black and gold marble.027"]} />
      </group>
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      //pilaar room outside wall
      <mesh
        geometry={nodes.Cylinder033.geometry}
        material={materials["Misty Veil Marble.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder034.geometry}
        material={materials["Pink Marble.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder035.geometry}
        material={materials["Marble tiles 9.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder036.geometry}
        material={materials["Marble.034"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder037.geometry}
        material={materials["Blue marble.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder038.geometry}
        material={materials["Marble Tile 2.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder039.geometry}
        material={materials["Marble Tile.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder040.geometry}
        material={materials["Luxury marble.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder041.geometry}
        material={materials["Procedural Marble Tiles.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder042.geometry}
        material={materials["White marble.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder043.geometry}
        material={materials["white_marble.002"]}
        position={[16.798, 21.946, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      //flower in the pillar, cylinder044, Cylinder045
      <mesh
        geometry={nodes.Cylinder044.geometry}
        // material={materials["Marble.035"]}
        // material={materials["Black murble.002"]}
        material={materials["White Bronze Marble.003"]}
        position={[16.798, 1.277, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder045.geometry}
        material={nodes.Cylinder045.material}
        position={[16.798, 9.238, -11.268]}
        rotation={[0, 0, 0.012]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[16.798, 21.687, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder047.geometry}
        material={nodes.Cylinder047.material}
        position={[16.798, -2.976, -11.268]}
        scale={[1.013, 1.348, 1.071]}
      />
      //pilar stairs in between
      <group position={[16.798, 16.587, -11.268]} scale={[1.067, 0.048, 0.913]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials["White Bronze Marble.003"]} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials["Black Marble Procedural.003"]} />
        <mesh geometry={nodes.Cube014_3.geometry} material={materials["Dark Brown Marble.003"]} />
      </group>
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials["Black marble tiles with golden ornaments.002"]}
        position={[16.783, 19.586, -11.258]}
        scale={[0.759, 0.028, 0.689]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["Black Marble.002"]}
        position={[16.798, 16.587, -11.268]}
        scale={[0.868, 0.039, 0.742]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[16.783, 19.586, -11.258]}
        scale={[0.759, 0.028, 0.689]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Black murble.002"]}
        position={[16.798, 16.587, -11.268]}
        scale={[1.067, 0.048, 0.913]}
      />
      <group position={[14.552, 21.331, 11.99]} rotation={[0, 1.566, 0]} scale={[0.018, 0.041, 0.017]}>
        <mesh geometry={nodes.Torus030_1.geometry} material={materials["Marble.039"]} />
        <mesh geometry={nodes.Torus030_2.geometry} material={materials["Golden brushed metal.030"]} />
        <mesh geometry={nodes.Torus030_3.geometry} material={materials["Golden Honeycomb.030"]} />
        <mesh geometry={nodes.Torus030_4.geometry} material={materials["Ceramic Tile Golden.030"]} />
        <mesh geometry={nodes.Torus030_5.geometry} material={materials["Black and gold marble.030"]} />
        <mesh geometry={nodes.Torus030_6.geometry} material={materials["Marble.036"]} />
        <mesh geometry={nodes.Torus030_7.geometry} material={materials["Golden brushed metal.028"]} />
        <mesh geometry={nodes.Torus030_8.geometry} material={materials["Golden Honeycomb.028"]} />
        <mesh geometry={nodes.Torus030_9.geometry} material={materials["Ceramic Tile Golden.028"]} />
        <mesh geometry={nodes.Torus030_10.geometry} material={materials["Black and gold marble.028"]} />
        <mesh geometry={nodes.Torus030_11.geometry} material={materials["Marble.038"]} />
        <mesh geometry={nodes.Torus030_12.geometry} material={materials["Golden brushed metal.029"]} />
        <mesh geometry={nodes.Torus030_13.geometry} material={materials["Golden Honeycomb.029"]} />
        <mesh geometry={nodes.Torus030_14.geometry} material={materials["Ceramic Tile Golden.029"]} />
        <mesh geometry={nodes.Torus030_15.geometry} material={materials["Black and gold marble.029"]} />
        <mesh geometry={nodes.Torus030_16.geometry} material={materials["Marble.040"]} />
        <mesh geometry={nodes.Torus030_17.geometry} material={materials["Golden brushed metal.031"]} />
        <mesh geometry={nodes.Torus030_18.geometry} material={materials["Golden Honeycomb.031"]} />
        <mesh geometry={nodes.Torus030_19.geometry} material={materials["Ceramic Tile Golden.031"]} />
        <mesh geometry={nodes.Torus030_20.geometry} material={materials["Black and gold marble.031"]} />
      </group>
      <group position={[17.619, 17.923, 11.518]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus032_1.geometry} material={materials["Marble.041"]} />
        <mesh geometry={nodes.Torus032_2.geometry} material={materials["Golden brushed metal.032"]} />
        <mesh geometry={nodes.Torus032_3.geometry} material={materials["Golden Honeycomb.032"]} />
        <mesh geometry={nodes.Torus032_4.geometry} material={materials["Ceramic Tile Golden.032"]} />
        <mesh geometry={nodes.Torus032_5.geometry} material={materials["Black and gold marble.032"]} />
      </group>
      <group position={[17.61, 17.943, 9.306]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus033_1.geometry} material={materials["Marble.042"]} />
        <mesh geometry={nodes.Torus033_2.geometry} material={materials["Golden brushed metal.033"]} />
        <mesh geometry={nodes.Torus033_3.geometry} material={materials["Golden Honeycomb.033"]} />
        <mesh geometry={nodes.Torus033_4.geometry} material={materials["Ceramic Tile Golden.033"]} />
        <mesh geometry={nodes.Torus033_5.geometry} material={materials["Black and gold marble.033"]} />
      </group>
      <group position={[14.935, 17.909, 9.33]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus034_1.geometry} material={materials["Marble.043"]} />
        <mesh geometry={nodes.Torus034_2.geometry} material={materials["Golden brushed metal.034"]} />
        <mesh geometry={nodes.Torus034_3.geometry} material={materials["Golden Honeycomb.034"]} />
        <mesh geometry={nodes.Torus034_4.geometry} material={materials["Ceramic Tile Golden.034"]} />
        <mesh geometry={nodes.Torus034_5.geometry} material={materials["Black and gold marble.034"]} />
      </group>
      <group position={[14.949, 17.936, 11.525]} scale={[0.058, 0.137, 0.06]}>
        <mesh geometry={nodes.Torus035_1.geometry} material={materials["Marble.044"]} />
        <mesh geometry={nodes.Torus035_2.geometry} material={materials["Golden brushed metal.035"]} />
        <mesh geometry={nodes.Torus035_3.geometry} material={materials["Golden Honeycomb.035"]} />
        <mesh geometry={nodes.Torus035_4.geometry} material={materials["Ceramic Tile Golden.035"]} />
        <mesh geometry={nodes.Torus035_5.geometry} material={materials["Black and gold marble.035"]} />
      </group>
      <mesh
        geometry={nodes.Cylinder048.geometry}
        material={nodes.Cylinder048.material}
        position={[16.289, -3.175, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder049.geometry}
        material={nodes.Cylinder049.material}
        position={[16.289, 21.488, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder050.geometry}
        material={nodes.Cylinder050.material}
        position={[16.289, 9.039, 10.436]}
        rotation={[0, 0, 0.012]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder051.geometry}
        // material={materials["Marble.045"]}
        material={materials["White Bronze Marble.003"]}
        position={[16.289, 1.078, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder052.geometry}
        material={materials["white_marble.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder053.geometry}
        material={materials["White marble.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder054.geometry}
        material={materials["Procedural Marble Tiles.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder055.geometry}
        material={materials["Luxury marble.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder056.geometry}
        material={materials["Marble Tile.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder057.geometry}
        material={materials["Marble Tile 2.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder058.geometry}
        material={materials["Blue marble.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder059.geometry}
        material={materials["Marble.046"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder060.geometry}
        material={materials["Marble tiles 9.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder061.geometry}
        material={materials["Pink Marble.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder062.geometry}
        material={materials["Misty Veil Marble.003"]}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cylinder063.geometry}
        material={nodes.Cylinder063.material}
        position={[16.289, 21.747, 10.436]}
        scale={[1.013, 1.348, 1.071]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={materials["Black murble.003"]}
        position={[16.289, 16.388, 10.436]}
        scale={[1.067, 0.048, 0.913]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[16.274, 19.387, 10.447]}
        scale={[0.759, 0.028, 0.689]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={materials["Black Marble.003"]}
        position={[16.289, 16.388, 10.436]}
        scale={[0.868, 0.039, 0.742]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={materials["Black marble tiles with golden ornaments.003"]}
        position={[16.274, 19.387, 10.447]}
        scale={[0.759, 0.028, 0.689]}
      />
      <group position={[16.289, 16.388, 10.436]} scale={[1.067, 0.048, 0.913]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials["White Bronze Marble.004"]} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials["Black Marble Procedural.004"]} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials["Dark Brown Marble.004"]} />
      </group>
      {/* //trishul small */}
      <group position={[18.808, 6.723, 10.739]} rotation={[0, 0.027, 0]} scale={[2.193, 3.293, 2.42]}>
        <mesh geometry={nodes.Circle005_1.geometry} material={materials["Cast Iron Wrought Pattern Diamond.001"]} />
        <mesh geometry={nodes.Circle005_2.geometry} material={materials["Cast Iron Wrought Pattern Diamond.004"]} />
        <mesh geometry={nodes.Circle005_3.geometry} material={materials["White Bronze Marble.003"]} />
      </group>
      {/* //trishul large */}
      <group position={[0.617, 5.699, -2.919]} rotation={[0, 0.027, 0]} scale={[5.007, 10, 5.525]}>
        {/* <mesh geometry={nodes.Circle002_1.geometry} material={materials["Black Marble Procedural.006"]} /> */}
        <mesh geometry={nodes.Circle002_1.geometry} material={materials["White Bronze Marble.003"]} />
        <mesh geometry={nodes.Circle002_2.geometry} material={materials["White Bronze Marble.003"]} />
        {/* <mesh geometry={nodes.Circle002_3.geometry} material={materials["Heated Metal.005"]} /> */}
        <mesh geometry={nodes.Circle002_3.geometry} material={materials["White Bronze Marble.003"]} />
      </group>
    </group>
  );
}

useGLTF.preload("https://3dmodelpriya.s3.ap-south-1.amazonaws.com/temple21.glb");
